"""Specialist: generative fill / inpainting.

The case this is for: a real photograph with a region regenerated by a diffusion
model -- an object removed and the hole filled, a new object painted in, a sky
replaced. The rest of the frame is genuine, so a whole-image detector sees
mostly-real and dilutes the evidence. What makes the edit findable is not that
the region looks wrong on its own; it is that the region's *physics* stops
matching its immediate surroundings.

Four signatures, in the order they carry weight here:

1. **A noise-floor discontinuity.** The generated fill has a decoder's noise
   floor, not the camera's, and it is almost always the smoother of the two.
   Strong negative `noise_contrast` is this specialist's primary evidence.
2. **Missing fine detail.** Diffusion output manufactures its high frequencies
   by upsampling, so a fill tends to carry less true fine structure than the
   optics around it.
3. **A JPEG-grid discontinuity.** The original was compressed on a coherent 8x8
   lattice; the fill was pasted in after decode. Loud on a first-generation
   JPEG, meaningless on a PNG or after a re-save -- so it is weighted by how
   much grid there is to disagree about.
4. **A sharp map boundary.** The mapper's own falloff at the region rim. Fill
   boundaries are sharp because the mask that produced them was.

Confidence is driven by *agreement*: each signature votes, and the specialist is
confident to the extent that the votes point the same way. Two measurements
agreeing is worth far more than one being extreme, because each of these
individually has a benign explanation (a smooth region really can just be sky).
"""
from __future__ import annotations

import numpy as np

from specialists.base import SpecialistContext, SpecialistResult, blend_probability


def _squash(value: float, scale: float) -> float:
    """Map a signed contrast onto [0, 1] with 0 -> 0.5, saturating at ~2*scale."""
    return float(0.5 * (1.0 + np.tanh(value / max(scale, 1e-6))))


class InpaintingSpecialist:
    name = "inpainting"

    def __init__(
        self,
        noise_scale: float = 0.25,
        high_freq_scale: float = 0.30,
        grid_scale: float = 0.20,
        sharpness_scale: float = 0.04,
    ):
        self.noise_scale = noise_scale
        self.high_freq_scale = high_freq_scale
        self.grid_scale = grid_scale
        self.sharpness_scale = sharpness_scale

    def analyse(self, ctx: SpecialistContext) -> SpecialistResult:
        f = ctx.forensics()
        region = ctx.region

        if not f.get("valid"):
            return SpecialistResult(
                specialist=self.name,
                probability=float(region.mean_score),
                confidence=0.15,
                evidence=[f"forensic measurement unavailable: {f.get('reason', 'unknown')}"],
                details=dict(f),
            )

        evidence: list[str] = []
        votes: list[float] = []

        # 1. Noise floor. Negative contrast (smoother inside) is the inpainting
        #    signature; positive contrast is a foreign-noise signature, which is
        #    compositing's story rather than this one, so it does not count for.
        noise_c = f["noise_contrast"]
        noise_term = _squash(-noise_c, self.noise_scale)
        votes.append(noise_term)
        if noise_c < -0.08:
            evidence.append(
                f"residual noise floor {abs(noise_c) * 100:.0f}% lower inside the region "
                f"than in the ring around it -- decoder output, not sensor noise"
            )
        elif noise_c > 0.08:
            evidence.append(
                f"residual noise {noise_c * 100:.0f}% *higher* inside than outside -- "
                f"foreign noise, more consistent with a composite than a generative fill"
            )

        # 2. Fine detail.
        hf_c = f["high_freq_contrast"]
        votes.append(_squash(-hf_c, self.high_freq_scale))
        if hf_c < -0.08:
            evidence.append(
                f"fine-detail energy {abs(hf_c) * 100:.0f}% below the surrounding ring -- "
                f"the over-smoothing an upsampling decoder leaves"
            )

        # 3. JPEG grid -- only meaningful when there is a grid at all. On a PNG
        #    both sides read ~1.0 and this measurement must not vote.
        grid_strength = max(f["jpeg_grid_inside"], f["jpeg_grid_outside"]) - 1.0
        grid_c = f["jpeg_grid_contrast"]
        grid_weight = float(np.clip(grid_strength / 0.15, 0.0, 1.0))
        if grid_weight > 0.2 and abs(grid_c) > 0.08:
            evidence.append(
                f"JPEG 8x8 block grid discontinuous at the region boundary "
                f"(inside {f['jpeg_grid_inside']:.2f}x vs outside {f['jpeg_grid_outside']:.2f}x) -- "
                f"the region did not go through the same compression history"
            )

        # 4. The map's own boundary falloff.
        sharpness_term = float(np.clip(region.boundary_sharpness / self.sharpness_scale, 0.0, 1.0))
        if region.boundary_sharpness > self.sharpness_scale:
            evidence.append(
                f"the likelihood map falls off sharply at the region rim "
                f"(gradient {region.boundary_sharpness:.3f}/px), as a mask-shaped edit does"
            )

        probability = blend_probability(
            (noise_term, 1.0),
            (votes[1], 0.8),
            (_squash(abs(grid_c), self.grid_scale), grid_weight * 0.8),
            (0.5 + 0.5 * sharpness_term, 0.5),
            (float(region.mean_score), 1.2),   # the map itself is still evidence
            (ctx.score_crop(), 0.8),           # and so is the detector on the whole crop
        )

        # Confidence from agreement, not from extremity: how consistently do the
        # forensic votes point away from 0.5, and did enough of them run?
        active = [v for v in votes if abs(v - 0.5) > 0.02]
        agreement = 0.0
        if len(active) >= 2:
            directions = [np.sign(v - 0.5) for v in active]
            agreement = float(abs(np.mean(directions)))
        confidence = float(
            np.clip(
                0.25
                + 0.35 * agreement
                + 0.20 * grid_weight
                + 0.20 * min(1.0, region.area_frac / 0.05),
                0.0,
                0.9,
            )
        )

        if not evidence:
            evidence.append(
                "no forensic discontinuity found at the region boundary; the region rests "
                "on the likelihood map alone"
            )
            confidence = min(confidence, 0.3)

        return SpecialistResult(
            specialist=self.name,
            probability=probability,
            confidence=confidence,
            evidence=evidence,
            details={**f, "crop_score": ctx.score_crop(), "grid_weight": grid_weight},
        )
